name: SendGift
main: com.lonelydime.SendGift.SendGift
version: 1.1
website: https://github.com/lonelydime
author: lonelydime
description: >
             Allows players to send items from their own inventory.

commands:
  gift:
    description: sends an item stack in your inventory to another player
    usage: |
           /<command> [player] [item number] [item id or name]
           Example: /<command> lonelydime 10 264 - gives player lonelydime 10 diamonds.
  send:
    description: sends an item stack in your inventory to another player
    usage: |
           /<command> [player] [item number] [item id or name]
           Example: /<command> lonelydime 10 264 - gives player lonelydime 10 diamonds.